<?php

namespace ContainerNMdzXAs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oq6Ym6ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oq6Ym6Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oq6Ym6Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'utilisateurRepo' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'jwt' => 'App\\Service\\JWTService',
            'manager' => '?',
            'utilisateurRepo' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
