<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMdzXAs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMdzXAs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMdzXAs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMdzXAs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMdzXAs\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMdzXAs',
    'container.build_id' => 'b0590c28',
    'container.build_time' => 1725443603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMdzXAs');
