<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJXfW5S5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJXfW5S5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJXfW5S5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJXfW5S5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJXfW5S5\App_KernelDevDebugContainer([
    'container.build_hash' => 'JXfW5S5',
    'container.build_id' => 'c27ced4b',
    'container.build_time' => 1720531970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJXfW5S5');
